# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefa.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tarefa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctarefa.proto\"\'\n\x04Task\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\"5\n\x0cTaskResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x14\n\x05tasks\x18\x02 \x03(\x0b\x32\x05.Task\"\x14\n\x04\x41\x63\x61o\x12\x0c\n\x04\x61\x63\x61o\x18\x01 \x01(\t21\n\x0bTaskService\x12\"\n\nCreateTask\x12\x05.Task\x1a\r.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=16
  _globals['_TASK']._serialized_end=55
  _globals['_TASKRESPONSE']._serialized_start=57
  _globals['_TASKRESPONSE']._serialized_end=110
  _globals['_ACAO']._serialized_start=112
  _globals['_ACAO']._serialized_end=132
  _globals['_TASKSERVICE']._serialized_start=134
  _globals['_TASKSERVICE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
